---
# tasks file for semaphor
- name: Install Semaphor apt dependencies.
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ semaphor_apt_packages }}"

- name: Download Semaphor deb package.
  get_url:
    url: "{{ semaphor_deb_package_url }}"
    dest: "{{ semaphor_download_directory }}/{{ semaphor_deb_package_filename }}"
    checksum: "sha256:{{ semaphor_deb_package_sha256 }}"
  register: _semaphor_download_result

- name: Install Semaphor deb package.
  apt:
    deb: "{{ semaphor_download_directory }}/{{ semaphor_deb_package_filename }}"
